### ISSUE TITLE
Check out Thresholding for sensitivity data

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#32]
Right now we have sensitivity data in the range of 0 to 10k or more. This should be in the range of 0-30 micromolar. We need to find out what's wrong with the data and apply a sensible threshold.

**Comment by wassermai** [comment]
First of all I thought that we could neglect this issue. It is not uncommon to find these kind of numeric errors in structure-activity databases. Many databases are actually manually curated and it happens that measurements that are reported in nanomolar in a journal are wrongly transferred to the database and then reported as micromolar or another unit. As a consequence, you can get really weird activity values. So I thought we were just dealing with the usual noise. However, I then checked the activity file that Felix gave us. It is indeed not common that 8% of all measurements are above 100 micromolar. I will write to him ASAP in order to find out whether he has an explanation for this. I furthermore noticed that he applied a threshold of 10 uM to distinguish between actives and inactives. We should probably align our active/inactive definition with the range that we display in form of bar charts. That brings me to another question: when you encode how many compounds in a cluster map to a pathway, do you currently also count the inactives?

**Comment by alexsb** [comment]
Thanks. Regarding what we show: when you filter out the inactives, we don't show them. If you don't filter them out, we do show them.
