### ISSUE TITLE
Sort pathways by over-representation

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#43]
We can easily rank pathways by over-representation of a set of genes. If we filter the set of genes by the compounds, this would also correspond to a over-representation based on the compounds. 

@wassermai  - do you think we should weigh the genes by how many compounds act on them?

**Comment by alexsb** [comment]
Requires #42

**Comment by wassermai** [comment]
What I had in mind or understand is the following:
we have the following mapping: compounds -> genes -> pathways
clusters consist of compounds, i.e. we can check for overrepresentation of a pathway in a cluster of compounds using the two step mapping given above
do we really have to weigh the genes then? because if a lot of compounds act on the gene, then you need a high number of compounds in a cluster active against the gene to get a significant overrepresentation

please let me know if I am not getting the point

**Comment by wassermai** [comment]
we want to see what clusters show an enrichment in compounds that modulate a specific pathway. What we could do for each combination of a cluster and pathway: count how many of the compounds in the cluster modulate at least one target occurring in the pathway (a) and how many don't modulate any target of that pathway (b). 
Precalculated we could have a statistic how many compound in the whole set modulate the pathway (c) and how many don't (d). We can then calculate an enrichment factor for compounds modulating this pathway in the cluster by (a/(a+b) / (c/(c+d)). Or use a, b, (c-a), and (d-b) as input for a contingency table for an exact Fisher's test to get a p-value for the enrichment.
